# Generated by Django 3.2.4 on 2021-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210623_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('eventname', models.CharField(max_length=50)),
                ('eventtype', models.CharField(max_length=30)),
                ('eventlocation', models.CharField(max_length=100)),
                ('guestlimit', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.CharField(max_length=6)),
                ('disc', models.CharField(max_length=1000)),
            ],
        ),
    ]
